export const DEFAULT_REGEX_DEFINITIONS = [
  {
    type: "EMAIL",
    pattern: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b",
    flags: "gi",
    severity: "medium",
    description: "Email addresses",
  },
  {
    type: "PHONE",
    pattern: "\\b(?:(?:\\+?6?01[0-9])[-\\s]?[0-9]{6,8}|(?:\\+?65|0)?[679]\\d{7})\\b",
    flags: "ig",
    severity: "medium",
    description: "Malaysia/Singapore phone numbers",
  },
  {
    type: "UUID",
    pattern: "\\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\b",
    flags: "ig",
    severity: "high",
    description: "UUID/GUID",
  },
  {
    type: "API_KEY_GENERIC",
    pattern: "\\b(?:(?:api[-]?key)|(?:secret[-]?key))[:=]\\s*['\\\"]?[A-Za-z0-9\\-_]{16,}['\\\"]?\\b",
    flags: "ig",
    severity: "high",
    description: "Generic API keys",
  },
  {
    type: "AWS_KEY",
    pattern: "\\b(?:AKIA|ASIA)[A-Z0-9]{16}\\b",
    flags: "gi",
    severity: "high",
    description: "AWS-style access keys",
  },
  {
    type: "CREDIT_CARD",
    pattern:
      "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\\b",
    flags: "g",
    severity: "critical",
    description: "Major credit cards",
  },
  {
    type: "ACCOUNT_NUM",
    pattern: "\\b(?:\\d{8}|\\d{10,16})\\b",
    flags: "g",
    severity: "critical",
    description: "Generic financial account numbers",
  },
  {
    type: "SSN_US",
    pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b",
    flags: "g",
    severity: "critical",
    description: "US Social Security numbers",
  },
  {
    type: "MALAYSIA_IC",
    pattern: "\\b\\d{6}-\\d{2}-\\d{4}\\b",
    flags: "g",
    severity: "critical",
    description: "Malaysia IC with dashes",
  },
  {
    type: "MALAYSIA_IC_COMPACT",
    pattern: "\\b\\d{12}\\b",
    flags: "g",
    severity: "critical",
    description: "Malaysia IC without dashes",
    contextKeywords: ["IC", "NRIC", "MyKad", "identification", "ID", "no ic", "kad pengenalan"],
    priority: 1,
  },
  {
    type: "PASSPORT",
    pattern: "\\b[A-Z0-9]{6,10}\\b",
    flags: "gi",
    severity: "high",
    description: "Generic passport numbers",
    contextKeywords: ["passport", "passport no", "passport number", "passport ID", "passport holder"],
    priority: 1,
  },
  {
    type: "VIRTUAL_ACCOUNT",
    pattern: "\\b\\d{15,20}\\b",
    flags: "g",
    severity: "critical",
    description: "Virtual Account Numbers for FPX / DuitNow VA",
    contextKeywords: ["VA", "virtual account", "duitnow", "FPX va", "e-banking", "bank transfer"],
    priority: 2,
  },
  {
    type: "EWALLET_ACCOUNT",
    pattern: "\\b\\d{8,15}\\b",
    flags: "g",
    severity: "critical",
    description: "General e-wallet account identifiers",
    contextKeywords: ["ewallet", "wallet id", "touch n go", "boost", "grabpay", "duitnow id"],
    priority: 2,
  },
  {
    type: "SWIFT_BIC",
    pattern: "\\b[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\\b",
    flags: "gi",
    severity: "medium",
    description: "SWIFT/BIC financial institution codes",
    contextKeywords: ["SWIFT", "BIC", "bank code", "international transfer"],
    priority: 2,
  },
  {
    type: "IBAN",
    pattern: "\\b[A-Z]{2}\\d{2}[A-Z0-9]{11,30}\\b",
    flags: "gi",
    severity: "high",
    description: "International Bank Account Numbers",
    contextKeywords: ["IBAN", "international account", "SEPA", "EU transfer"],
    priority: 2,
  },
];

export default DEFAULT_REGEX_DEFINITIONS;
